runtime: python37

entrypoint: gunicorn -b :$PORT app:app

vpc_access_connector:
  name: projects/bills-app-305000/locations/europe-west1/connectors/db-connector

env_variables:
  DB_USER: mastergk
  DB_NAME: demo
  DB_HOST: "10.56.209.3:3306"


