runtime: python37

vpc_access_connector:
  name: projects/bills-app-305000/locations/europe-west2/connectors/bill-app-db

env_variables:
  DB_USER: mastergk
  DB_PASS: 9br*+9Fc9LX^2sy>iY,D
  DB_NAME: demo
  DB_HOST: "10.56.209.3:3306"


